### ISSUE TITLE
Discord link formatting problems

### ISSUE THREAD

**Issue by got2bhockey** [Squad-Community-Ban-List/Squad-Community-Ban-List#19]
Two community discord links appear to be broken in some way:
Anatolia - https://squad-community-ban-list.com/search/discord.gg/qRr3hyV    - Also a dead link, already pinged LeventHAN
PA - https://squad-community-ban-list.com/search/projectawesome.com/discord

Viewable on https://squad-community-ban-list.com/partner-organisation-list

**Comment by Thomas-Smyth** [comment]
Should be fixed now, thanks.
