### ISSUE TITLE
Banned Player Information Page

### ISSUE THREAD

**Issue by Thomas-Smyth** [Squad-Community-Ban-List/Squad-Community-Ban-List#21]
It would be good to have a page that we, server owners, etc. can give to players who say they are on/banned by the Squad Community Ban List.

Things/key phrases it may/should include:
 * Foreword
   * "If you have found this page then it likely means that someone has directed you here because you are listed on or have been banned by the Squad Community Ban List."
   * "The following page gives you a little more information about what this means."
   * "We are keen to ensure that **everyone** can enjoy a healthy Squad community and therefore we are keen to allow reformed players to rejoin that community. However, we are limited by how much we can do to help you, as explained below."
 * What is the Squad Community Ban List?
   * "The Squad Community Ban List is...".
   * Emphasis that we deal in facts and not opinions and therefore we cannot change the data we display/bans we issue.
 * If you are listed on the Squad Community Ban List...
   * Explain why they are listed.
   * Explain what this means/what are the consequences.
   * Explain how they can get unlisted. Again, place emphasis that we deal in facts and not opinions and therefore we cannot help them get a ban removed and instead they must speak to the appropriate server.
 * If you are banned by the Squad Community Ban List...
   * Explain why they are banned.
   * Explain what this means/what are the consequences.
   * Explain how they can get unbanned/still access servers. Again, place emphasis that we deal in facts and not opinions and therefore we cannot help them get a ban removed and instead they must speak to the appropriate server.
 * Ban List
   * It might be a good idea to allow people linking this page to be able to specify a Steam ID so it can be populated with a list of their bans, what servers they need to contact and links to their Discord.
 * Closing
   * "We hope the above information helps you resolve your issue..." 
   * Mention they can ask for more help in Discord.

We should then remove the sections from the FAQ that this covers such that the FAQ is targetted towards people using the Squad Community Ban List website and export ban lists.

**Comment by LeventHAN** [comment]
Fixed here: https://github.com/Thomas-Smyth/Squad-Community-Ban-List/pull/25
