### ISSUE TITLE
Placing "Disclaimers" closer to the "front line"

### ISSUE THREAD

**Issue by Thomas-Smyth** [Squad-Community-Ban-List/Squad-Community-Ban-List#24]
Currently, some important pieces of information that protect SCBL's reputation is a little far/hidden from the "front line", i.e. where people using the system get their information/make their judgement from.

For example, the information about how reasons are classified and the disclaimer on the accuracy of that process is hidden in the FAQ. We should move/put something that has the same effect on the search page in a tooltip next to the "Reason" title.

We should look for other cases where this would also be beneficial.

**Comment by Thomas-Smyth** [comment]
Another one to move: The disclaimer that SCBL is not responsible for issuing bans listed on the search page.

 * Remove it from the modal.
 * Make the link on each organisation name a new tab link to their Discord.
 * Place disclaimer at top/bottom of search page so it's immediately visible.

**Comment by LeventHAN** [comment]
> Currently, some important pieces of information that protect SCBL's reputation is a little far/hidden from the "front line", i.e. where people using the system get their information/make their judgement from.
> 
> For example, the information about how reasons are classified and the disclaimer on the accuracy of that process is hidden in the FAQ. We should move/put something that has the same effect on the search page in a tooltip next to the "Reason" title.
> 
> We should look for other cases where this would also be beneficial.

Is it possible to grab the original reason from gql? If so we can put a modal for each reason when someone clicks they can see the original ban reason as we see from BM? 
I don't think it would be issue since banned players also see that on their ban reason once gettin banned by the server...



> Another one to move: The disclaimer that SCBL is not responsible for issuing bans listed on the search page.
> 
> * Remove it from the modal.
> * Make the link on each organisation name a new tab link to their Discord.
> * Place disclaimer at top/bottom of search page so it's immediately visible.

We may use here a redirection page? Countdown of 10 seconds would be enough time to read 20-25 words I guess?

**Comment by Thomas-Smyth** [comment]
> Is it possible to grab the original reason from gql? If so we can put a modal for each reason when someone clicks they can see the original ban reason as we see from BM?
I don't think it would be issue since banned players also see that on their ban reason once gettin banned by the server...

This wouldn't really help as a lot of communities don't actually put a reason in the reason. They sometimes just do it in a note, but we cannot share those.

> We may use here a redirection page? Countdown of 10 seconds would be enough time to read 20-25 words I guess?
I think it would just be better to display the disclaimer on the search page. The redirects to Discord are only to replace what is already in the modal given that the model will become irrelevant by the more prominent disclaimer.

**Comment by LeventHAN** [comment]
I guess this https://github.com/Thomas-Smyth/Squad-Community-Ban-List/pull/25/commits/4699a90ad8376d014b28f4f50069fba9f4224bec fixes this ticket?

**Comment by Thomas-Smyth** [comment]
Now https://github.com/Thomas-Smyth/Squad-Community-Ban-List/commit/b76c2e6ee8fcfb1d8f64e875007e3ae3b4012429 is in place I'm happy this has been addressed sufficiently.
