### ISSUE TITLE
Community's exporting preemptive bans to the ban list.

### ISSUE THREAD

**Issue by Babodias** [Squad-Community-Ban-List/Squad-Community-Ban-List#26]
I have noticed that some community's decide to pre-emptively ban individuals by looking on the ban list, I think this is fine and should continue to happen. But community's will then export that preemptive ban to the SCBL, completely screwing over the person who was pre-emptively banned. I was wondering if there was a way to stop this from happening because it seems super un fair. For instance on the picture provided two servers pre-emptively banned this player for past bans, completely fine, but they exported it to the ban list giving the player 6 extra points. Which puts him/her bellow the 9 point standard threshold. That's all I wanted to share, thanks for keeping up the hard work, Babodias. PS: Sorry if this isn't in the right place to say this.

![Capture 338](https://user-images.githubusercontent.com/78283304/106370843-f4fe9280-632b-11eb-9f09-0f2201043856.PNG)

**Comment by werewolfboy13** [comment]
As a person that learning Regex that could mean that reason or discription doesn't have an entry or is using terms that the system looks for. It will throw an Unknown if so.

**Comment by Babodias** [comment]
I talked to one of the server owners and they said it was a pre-emptive ban. I was more wondering if it went against the rules to export a ban like that. This preemptive banning has happened other times. Edit: Thanks for the quick response!

**Comment by werewolfboy13** [comment]
That question is beyond me. You might have better luck in the discord. https://discord.gg/DjrpPuw

**Comment by Babodias** [comment]
Which channel exactly? I was having some issues finding a spot to talk about it.

**Comment by werewolfboy13** [comment]
![image](https://user-images.githubusercontent.com/43587009/106371636-64748200-632c-11eb-812a-797394505bc2.png)
I would do in the General.

**Comment by Thomas-Smyth** [comment]
Closed in favour of https://github.com/Thomas-Smyth/Squad-Community-Ban-List/issues/28
